# Generated by Django 3.0 on 2019-12-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunt_toolkit', '0003_auto_20191203_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='job_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
