# Generated by Django 3.0 on 2019-12-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunt_toolkit', '0004_auto_20191203_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
