# Generated by Django 3.0 on 2019-12-03 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunt_toolkit', '0005_application_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='company_name',
        ),
    ]
