# Generated by Django 3.0 on 2019-12-03 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunt_toolkit', '0007_auto_20191203_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='company_name',
        ),
    ]
