# Generated by Django 3.0 on 2019-12-04 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunt_toolkit', '0008_remove_application_company_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Checklick',
            new_name='Checklist',
        ),
    ]
