# Generated by Django 3.0 on 2019-12-04 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunt_toolkit', '0009_auto_20191204_0009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checklist',
        ),
    ]
