# Generated by Django 3.0 on 2019-12-06 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunt_toolkit', '0010_delete_checklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
    ]
